### PR TITLE
Update PluginUtils.java

### PR DESCRIPTION
**Pull request by alan67160**
allow PluginUtils.fromString() accept loc without yaw and pitch

### CODE REVIEW

**Comment by MartenM** [comment]
Wouldn't this effectively set the location to yaw and pitch 0 0?

**Comment by alan67160** [comment]
sorry that was a mistake. I'm trying to keep the viewing angle, so I think removing the pitch and yaw will do it, but the truth is not.
so maybe changing the following line will do the work?
[src/main/java/nl/martenm/servertutorialplus/points/ServerTutorialPoint.java#L103](https://github.com/MartenM/ServerTutorialPlus/blob/2c8dec7eb38252c2e103d9040f7bb6ed0e07b11c/src/main/java/nl/martenm/servertutorialplus/points/ServerTutorialPoint.java#L103)
by adding a check on that line
if pitch and yaw no provided in the config file then clone the player pitch and yaw to target location?

**Comment by MartenM** [comment]
Creating an argument for points that teleport which could be (keepYawPitch) could be a thing.
Although to be honest, teleporting to a spot and not resetting the yaw and pitch might confuse players.

**Comment by alan67160** [comment]
let me give you a reasonable example
checkpoint will teleport player after player arrived the checkpoint
I am using checkpoint to create a path guidance and sending a message to you in every checkpoint tomorrow look like on talking to you right by your side
in that case the player constantly change the view

**Comment by MartenM** [comment]
> let me give you a reasonable example checkpoint will teleport player after player arrived the checkpoint I am using checkpoint to create a path guidance and sending a message to you in every checkpoint to look like on talking to you right by your side in that case the player constantly change the view

Wouldn't disabling the teleport on the checkpoint make more sense? That's already possible.

**Comment by alan67160** [comment]
I have already tried it to disable the teleport but it still teleport
```yml
tutorials:
  t1:
    stats:
      plays: 13
    invisible: false
    permission: false
    block-chat: false
    blocks-commands: false
    rewards: []
    command-whitelist: []
    points:
      '6':
        type: CHECKPOINT
        location: plot 37.5 97.5 2.5 1.91 -5.11
        time: 0.5
        locplayer: false
        locview: false
        teleport: false
        messages: []
        commands:
        - custom_events_delaymsg 0.5 %player_name% <&a教學喵蟲&f> GoGo!!
        animation: CIRCLE
        colour: 244 153 0
        distance: 1.0
        repeatActionbar: true
        drawguide: true
        guidecolour: 244 244 244
```
(0 to 5 was removed as it doesn't related)

**Comment by alan67160** [comment]
on github I only see teleport argument loaded on ClickBlockPoint

**Comment by MartenM** [comment]
You should try to edit these things in-game using the commands. It will tell you if something is available or not.
If what you said is true,  a PR that enables this for the checkpoint would be better :)

**Comment by alan67160** [comment]
moved to #77

**Pull request closed without merging**
